; This file is autogenerated by collector.go script

Include "BlitzXML.bb"
Include "example.bb"
Include "hashmap.bb"
Include "xmlSerialize.bb"

; Script started with argument 'callmain' which means that the Main() function will be called after all Include directives.
; This means that Main() function must be present in the one of the included files, otherwise it will lead to an error.
Main()